version: 2

models:

    - name: sales
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
            
      columns:
          - name: orders_id
            description: creat a new order num
            tests : 
            - not_null 

          - name: products_id
            description: ID for products 
            tests : 
              - not_null 

          - name: qty
            

          - name: turnover
            description: calculate the turnover
            tests : 
              - not_null 


          - name: purchase_cost
            description: cost for purchases
            tests : 
              - not_null 

          - name: margin
            description: it's margin for purchases cost